"""
Pure Visual Monitoring Dashboard (The Eyes)
Reads data from the shared volume generated by the background brain (main.py).
"""

import streamlit as st
import pandas as pd
import json
import os
import plotly.graph_objects as go
from datetime import datetime
from streamlit_autorefresh import st_autorefresh

st.set_page_config(layout="wide", page_title="Quant Options Monitor")

# Auto-refresh the page every 2 seconds
st_autorefresh(interval=2000, key="data_refresh")

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data')
GREEKS_FILE = os.path.join(DATA_DIR, 'greeks.csv')
METRICS_FILE = os.path.join(DATA_DIR, 'metrics.json')
CONTROL_FILE = os.path.join(DATA_DIR, 'control.json')

# ==============================================================================
# SIDEBAR - REMOTE CONTROL
# ==============================================================================

# Read current control state
control_state = {"status": "running", "watchlist": ["SPY", "QQQ", "NVDA", "TSLA"]}
if os.path.exists(CONTROL_FILE):
    try:
        with open(CONTROL_FILE, 'r') as f:
            control_state = json.load(f)
    except Exception:
        pass

st.sidebar.title("🎮 Remote Control Panel")
st.sidebar.info("🤖 System is in fully decoupled mode. Changes here send commands to the background trading brain.")

tickers_input = st.sidebar.text_input(
    "Tickers to Monitor (comma-separated)", 
    value=", ".join(control_state.get("watchlist", []))
)

col1, col2 = st.sidebar.columns(2)
is_running = control_state.get("status", "running") == "running"

if col1.button("▶️ Start Engine", disabled=is_running):
    control_state["status"] = "running"
    
if col2.button("⏹️ Stop Engine", disabled=not is_running):
    control_state["status"] = "stopped"

# Save new state for the brain to read
new_watchlist = [t.strip().upper() for t in tickers_input.split(",") if t.strip()]
control_state["watchlist"] = new_watchlist

try:
    with open(CONTROL_FILE, 'w') as f:
        json.dump(control_state, f)
except Exception as e:
    st.sidebar.error(f"Failed to write control file: {e}")

if is_running:
    st.sidebar.success("🟢 Trading Brain is RUNNING")
else:
    st.sidebar.error("🔴 Trading Brain is STOPPED")

# ==============================================================================
# MAIN DASHBOARD
# ==============================================================================

st.title("📊 Institutional OMS & Risk Monitor")

# Read Metrics - Added .get() to prevent KeyError
metrics_data = {}
if os.path.exists(METRICS_FILE):
    try:
        with open(METRICS_FILE, 'r') as f:
            metrics_data = json.load(f)
    except Exception:
        pass

# Safely extract values with defaults
last_update = metrics_data.get('last_update', 'Waiting for Brain...')
t_delta = metrics_data.get('total_delta', 0.0)
t_gamma = metrics_data.get('total_gamma', 0.0)
t_theta = metrics_data.get('total_theta', 0.0)
n_opts = metrics_data.get('num_options', 0)
# New IBKR-native risk metrics emitted by main.py
daily_pnl = metrics_data.get('daily_pnl', 0.0)
nlv = metrics_data.get('net_liquidation', 0.0)
settled_cash = metrics_data.get('settled_cash', 0.0)
dollar_gamma = metrics_data.get('dollar_gamma', 0.0)
dollar_delta = metrics_data.get('dollar_delta', 0.0)
gamma_limit_pct = metrics_data.get('gamma_limit_pct', 0.05)
gamma_util_pct = metrics_data.get('gamma_utilization_pct', 0.0)
gamma_breached = metrics_data.get('gamma_breached', False)
active_trades = metrics_data.get('active_trades', 0)

# Brain-liveness check: if metrics.json hasn't been refreshed in 30+ seconds,
# the background brain is likely stuck in a connection loop or crashed.
brain_alive = False
if isinstance(last_update, str) and last_update != 'Waiting for Brain...':
    try:
        age_seconds = (datetime.now() - datetime.fromisoformat(last_update)).total_seconds()
        brain_alive = age_seconds < 30
    except Exception:
        pass

if not brain_alive and last_update != 'Waiting for Brain...':
    st.error("⚠️ Brain has not updated metrics in 30+ seconds — connection may be looping. Check `docker logs quant_brain`.")
else:
    st.info(f"🔄 Last Market Data Sync: {last_update}")

# Top row: account + P&L (IBKR-native)
acct_cols = st.columns(4)
acct_cols[0].metric("Net Liquidation", f"${nlv:,.2f}")
acct_cols[1].metric("Daily P&L (IBKR)", f"${daily_pnl:,.2f}",
                     delta=f"{(daily_pnl / nlv * 100):.2f}%" if nlv > 0 else None)
acct_cols[2].metric("Settled Cash", f"${settled_cash:,.2f}")
acct_cols[3].metric("Active Trades", active_trades)

# Risk row: Greeks + dollar exposures
risk_cols = st.columns(4)
risk_cols[0].metric("Net Portfolio Delta", f"{t_delta:.2f}")
risk_cols[1].metric("Dollar Delta", f"${dollar_delta:,.0f}")
risk_cols[2].metric("Portfolio Gamma (raw)", f"{t_gamma:.4f}")
risk_cols[3].metric("Daily Theta Decay", f"${t_theta * 100:.2f}")

# Gamma circuit-breaker indicator
gamma_limit_dollar = nlv * gamma_limit_pct if nlv > 0 else 0.0
gamma_status_cols = st.columns([1, 3])
with gamma_status_cols[0]:
    if gamma_breached:
        st.error("🔴 GAMMA BREACH")
    else:
        st.success("🟢 GAMMA SAFE")
with gamma_status_cols[1]:
    st.markdown(
        f"**Dollar Gamma:** `${dollar_gamma:,.0f}` &nbsp; — &nbsp;"
        f"**Utilization:** `{gamma_util_pct:.1f}% / {gamma_limit_pct*100:.1f}% NLV Limit` "
        f"(`${gamma_limit_dollar:,.0f}`)"
    )
    # progress bar capped at 100% display
    st.progress(min(gamma_util_pct / 100.0, 1.0))

# Read Greeks Dataframe
greeks_df = pd.DataFrame()
if os.path.exists(GREEKS_FILE):
    try:
        greeks_df = pd.read_csv(GREEKS_FILE)
    except Exception:
        pass

# 3D Surface Graph
if "vol_surface_fig" not in st.session_state:
    st.session_state.vol_surface_fig = None

col_title, col_btn = st.columns([0.8, 0.2])
with col_title:
    st.subheader("🌐 Real-Time Volatility Surface (3D)")
with col_btn:
    refresh_surface = st.button("🔄 Refresh Surface")

if refresh_surface:
    if not greeks_df.empty and len(greeks_df) > 3:
        plot_df = greeks_df.dropna(subset=['strike', 'expiration', 'iv']).copy()
        today = pd.Timestamp.now().normalize()
        plot_df['dte'] = (pd.to_datetime(plot_df['expiration']) - today).dt.days
        
        fig_3d = go.Figure(data=[go.Scatter3d(
            x=plot_df['strike'], 
            y=plot_df['dte'],  
            z=plot_df['iv'], 
            mode='markers',
            marker=dict(size=6, color=plot_df['iv'], colorscale='Viridis', opacity=0.8)
        )])
        
        fig_3d.update_layout(
            scene=dict(xaxis_title='Strike', yaxis_title='DTE', zaxis_title='IV'), 
            height=500, 
            margin=dict(l=0, r=0, b=0, t=0)
        )
        st.session_state.vol_surface_fig = fig_3d
    else:
        st.session_state.vol_surface_fig = "empty"

if st.session_state.vol_surface_fig == "empty":
    st.warning("💡 Insufficient data. Wait for the brain to collect more market data and click Refresh.")
elif st.session_state.vol_surface_fig is not None:
    st.plotly_chart(st.session_state.vol_surface_fig, use_container_width=True)

# Active Options Table
st.subheader("📋 Active Options Stream")
if not greeks_df.empty:
    st.dataframe(greeks_df, use_container_width=True, hide_index=True)
else:
    st.warning("⏳ Waiting for initial data from the background brain...")

# ==============================================================================
# TRADE HISTORY (trailing 12 months — performance-bounded; missing files are OK)
# ==============================================================================
st.subheader("📒 Trade History (Trailing 12 Months)")


def _load_trailing_history(months: int = 12) -> pd.DataFrame:
    """Read trade_history_YYYY_MM.csv for the last N months. Skip missing months."""
    frames = []
    today = datetime.now()
    for k in range(months):
        # walk back month by month
        y = today.year
        m = today.month - k
        while m <= 0:
            m += 12
            y -= 1
        path = os.path.join(DATA_DIR, f"trade_history_{y}_{m:02d}.csv")
        try:
            frames.append(pd.read_csv(path))
        except FileNotFoundError:
            # No trades that month — perfectly normal; skip silently
            continue
        except Exception as e:
            st.caption(f"(could not read {os.path.basename(path)}: {e})")
            continue
    if not frames:
        return pd.DataFrame()
    df = pd.concat(frames, ignore_index=True)
    # Most-recent-first
    if "timestamp_local" in df.columns:
        df = df.sort_values("timestamp_local", ascending=False)
    return df


history_df = _load_trailing_history(months=12)
if history_df.empty:
    st.info("No trades in the trailing 12 months yet.")
else:
    st.caption(f"Showing {len(history_df)} fills (consolidated; VWAP-priced).")
    st.dataframe(history_df, use_container_width=True, hide_index=True, height=320)